
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Microsoft
 */
public class Volume extends javax.swing.JFrame {

    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        buttonsend2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jarijari = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        buttonsend1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panjang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lebar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonsend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Penghitung volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 320, 60);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel2.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel18.setText("Masukkan Panjang Sisi:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 70, 140, 26);
        jPanel2.add(sisi);
        sisi.setBounds(150, 70, 190, 30);

        jLabel19.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel19.setText("cm");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(350, 70, 20, 20);

        buttonsend2.setText("Hitung");
        buttonsend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsend2ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonsend2);
        buttonsend2.setBounds(170, 110, 70, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel16.setText("Masukkan Jari-jari :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 70, 120, 26);
        jPanel3.add(jarijari);
        jarijari.setBounds(150, 70, 190, 30);

        jLabel17.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel17.setText("cm");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(350, 70, 20, 20);

        buttonsend1.setText("Hitung");
        buttonsend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsend1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonsend1);
        buttonsend1.setBounds(170, 120, 70, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel11.setText("cm");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 100, 20, 20);
        jPanel1.add(panjang);
        panjang.setBounds(140, 20, 190, 30);

        jLabel9.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel9.setText("Masukkan lebar :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 60, 110, 26);
        jPanel1.add(lebar);
        lebar.setBounds(140, 60, 190, 30);

        jLabel12.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel12.setText("Masukkan tinggi :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 100, 110, 26);
        jPanel1.add(tinggi);
        tinggi.setBounds(140, 100, 190, 30);

        jLabel13.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel13.setText("Masukkan Panjang:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 20, 120, 26);

        jLabel14.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel14.setText("cm");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(340, 20, 20, 20);

        jLabel15.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel15.setText("cm");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 60, 20, 20);

        buttonsend.setText("Hitung");
        buttonsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsendActionPerformed(evt);
            }
        });
        jPanel1.add(buttonsend);
        buttonsend.setBounds(170, 150, 70, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsend2ActionPerformed
        int Sisi;
        Sisi = Integer.parseInt(sisi.getText());
        int hasil = Sisi*Sisi*Sisi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah :"+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonsend2ActionPerformed

    private void buttonsend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsend1ActionPerformed
        float Jarijari;
        Jarijari = Integer.parseInt(jarijari.getText());
        float hasil = (float) (4/3*Math.PI*Jarijari*Jarijari*Jarijari);
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah :"+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonsend1ActionPerformed

    private void buttonsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsendActionPerformed
        int Panjang, Lebar, Tinggi;
        Panjang = Integer.parseInt(panjang.getText());
        Lebar = Integer.parseInt(lebar.getText());
        Tinggi = Integer.parseInt(tinggi.getText());
        int hasil = Panjang*Lebar*Tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonsendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonsend;
    private javax.swing.JButton buttonsend1;
    private javax.swing.JButton buttonsend2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jarijari;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField panjang;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables
}
